version: '3.8'

services:
  # The FastAPI Application
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app/app
      - ./outputs:/usr/src/app/outputs # Mount outputs to persist generated files
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/appdb
    depends_on:
      - db
      - redis
    command: uvicorn app.backend.main:app --host 0.0.0.0 --port 8000 --reload

  # The Celery Worker
  worker:
    build: .
    command: celery -A app.backend.tasks.celery_app worker --loglevel=info
    volumes:
      - ./app:/usr/src/app/app
      - ./outputs:/usr/src/app/outputs
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/appdb
    depends_on:
      - web
      - redis

  # PostgreSQL Database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb

  # Redis for Celery Broker
  redis:
    image: redis:6.2-alpine

volumes:
  postgres_data:
