serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/worker-service-sa@$PROJECT_ID.iam.gserviceaccount.com'

steps:
  # Step 1: Build the application container using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/youtube-ai-app/production:$COMMIT_SHA'
      - '.'

  # Step 2: Push the container image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/youtube-ai-app/production:$COMMIT_SHA'

  # Step 3: Run the full pipeline to generate, upload, and commercialize the video.
  # This step uses the image we just built and securely injects the secrets.
  - name: 'us-central1-docker.pkg.dev/$PROJECT_ID/youtube-ai-app/production:$COMMIT_SHA'
    id: 'Run Full Pipeline'
    entrypoint: 'python' # Override the Dockerfile's CMD to run a specific script
    args:
      - 'app/full_pipeline.py'
      - '--topic'
      - '${_VIDEO_TOPIC}' # Use a substitution variable for the topic
    secretEnv:
      - 'OPENAI_API_KEY'
      - 'YOUTUBE_CLIENT_ID'
      - 'YOUTUBE_CLIENT_SECRET'
      - 'GEMINI_API_KEY'
      - 'MIDJOURNEY_API_KEY'
      - 'STRIPE_API_KEY'
      - 'SHOPIFY_API_KEY'
      - 'PAYONEER_CUSTOMER_ID'
      - 'FREELANCER_ACCESS_TOKEN'

# Define which secrets from Secret Manager are available to this build
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: 'OPENAI_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/YOUTUBE_CLIENT_ID/versions/latest
      env: 'YOUTUBE_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/YOUTUBE_CLIENT_SECRET/versions/latest
      env: 'YOUTUBE_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
      env: 'GEMINI_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/MIDJOURNEY_API_KEY/versions/latest
      env: 'MIDJOURNEY_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_API_KEY/versions/latest
      env: 'STRIPE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/SHOPIFY_API_KEY/versions/latest
      env: 'SHOPIFY_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/PAYONEER_CUSTOMER_ID/versions/latest
      env: 'PAYONEER_CUSTOMER_ID'
    - versionName: projects/$PROJECT_ID/secrets/FREELANCER_ACCESS_TOKEN/versions/latest
      env: 'FREELANCER_ACCESS_TOKEN'

# Set a longer timeout and use a more powerful machine for video processing.
options:
  timeout: 7200s # 2 hours
  machineType: 'E2_HIGHCPU_8'