serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/worker-service-sa@$PROJECT_ID.iam.gserviceaccount.com'

steps:
  # Step 1: Build the application container using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/youtube-ai-app/production:$COMMIT_SHA'
      - '.'

  # Step 2: Push the container image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/youtube-ai-app/production:$COMMIT_SHA'

  # Step 3: Run the full pipeline to generate, upload, and commercialize the video.
  # This step uses the image we just built and securely injects the secrets.
  - name: 'us-central1-docker.pkg.dev/$PROJECT_ID/youtube-ai-app/production:$COMMIT_SHA'
    id: 'Run Full Pipeline'
    entrypoint: 'python' # Override the Dockerfile's CMD to run a specific script
    args:
      - '-m'
      - 'app.full_pipeline' # Run as a module to fix import paths
      - '--topic'
      - '${_VIDEO_TOPIC}' # Use a substitution variable for the topic
    secretEnv:
      - 'GEMINI_API_KEY'
    # Provide required environment variables for the application settings to load.
    # The pipeline script doesn't use the database or secret key, so dummy values are sufficient.
    env:
      - 'SECRET_KEY=dummy-secret-for-build'
      - 'DATABASE_URL=sqlite+aiosqlite:///:memory:'
      - 'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'

# Define which secrets from Secret Manager are available to this build
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
      env: 'GEMINI_API_KEY'

timeout: 7200s # 2 hours

# Set a more powerful machine for video processing.
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Define substitution variables that can be set in the Trigger settings.
# _VIDEO_TOPIC is already expected.
# _GCS_BUCKET_NAME is newly required by the pipeline script.
substitutions:
  _VIDEO_TOPIC: 'The Future of Artificial Intelligence'
  _GCS_BUCKET_NAME: 'your-gcs-bucket-name-here' # IMPORTANT: Update this in your trigger