name: Automated Code Review & Milestone Tracking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lint
        run: |
          pip install flake8
          flake8 app/
      - name: Run Tests
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -d app/tests ]; then pytest app/tests; fi
      - name: Milestone/Project Board Sync (placeholder)
        run: echo "Syncing with project board..."
      # Extend here for LLM/agent review integrations 