name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install -r mini_app/requirements.txt # Install mini_app dependencies (if any)
          pip install ruff black pytest # Install linting and testing tools

      - name: Lint Python code
        run: |
          source venv/bin/activate
          ruff check .
          black --check .

      - name: Run Python tests
        run: |
          source venv/bin/activate
          pytest app/tests/ # Assuming your tests are in app/tests/ and use pytest

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies and lint/test
        run: |
          cd frontend/dev_dashboard
          yarn install --frozen-lockfile
          yarn lint # Assuming you have a lint script in package.json
          yarn test # Assuming you have a test script in package.json