name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prelaunch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Install frontend dependencies
        run: |
          cd frontend/dev_dashboard
          npm install
      - name: Pre-launch validation
        run: bash app/lifecycle/tasks/prelaunch_validate.sh
      - name: Build
        run: bash app/lifecycle/tasks/prelaunch_build.sh
      - name: Run backend tests
        run: pytest app/tests
      # - name: AI Review (optional, requires local runner)
      #   run: python app/lifecycle/tasks/prelaunch_ai_review.py
      #   env:
      #     USE_LMSTUDIO: "1"  # Set to use LM Studio, unset for Ollama
      # Add deployment steps here (to your server, cloud, etc.) 