name: Reusable - Build and Push Docker Image

on:
  workflow_call:
    inputs:
      service_name:
        description: 'The name of the service to build the image for'
        required: true
        type: string
    outputs:
      image_tag:
        description: "The full tag of the pushed image"
        value: ${{ jobs.build-and-push.outputs.image_tag }}

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1

jobs:
  build-and-push:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      image_tag: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ inputs.service_name }}/image:${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      - run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
      - run: |-
          docker build --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ inputs.service_name }}/image:$GITHUB_SHA" .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ inputs.service_name }}/image:$GITHUB_SHA"